# Generated by Django 4.0.4 on 2022-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('DepartamentoId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartamentoNome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Empregados',
            fields=[
                ('EmpregadoId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpregadoNome', models.CharField(max_length=500)),
                ('Departamento', models.CharField(max_length=500)),
                ('DataDeAdmissao', models.DateField()),
                ('FotoPerfil', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=500)),
                ('Senha', models.CharField(max_length=500)),
            ],
        ),
    ]
